In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
data=pd.read_csv("A:\Dataset\car_purchase_data.csv")
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\astik\AppData\Local\Temp\ipykernel_2944\4262763198.py:1: SyntaxWarning: invalid escape sequence '\D'
  data=pd.read_csv("A:\Dataset\car_purchase_data.csv")


In [9]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [15]:
print(X_train)

[[-1.1631724  -1.5849703 ]
 [ 2.17018137  0.93098672]
 [ 0.0133054   1.22017719]
 [ 0.20938504  1.07558195]
 [ 0.40546467 -0.48604654]
 [-0.28081405 -0.31253226]
 [ 0.99370357 -0.8330751 ]
 [ 0.99370357  1.8563962 ]
 [ 0.0133054   1.24909623]
 [-0.86905295  2.26126285]
 [-1.1631724  -1.5849703 ]
 [ 2.17018137 -0.80415605]
 [-1.35925203 -1.46929411]
 [ 0.40546467  2.2901819 ]
 [ 0.79762394  0.75747245]
 [-0.96709276 -0.31253226]
 [ 0.11134522  0.75747245]
 [-0.96709276  0.55503912]
 [ 0.30742485  0.06341534]
 [ 0.69958412 -1.26686079]
 [-0.47689368 -0.0233418 ]
 [-1.7514113   0.3526058 ]
 [-0.67297331  0.12125343]
 [ 0.40546467  0.29476771]
 [-0.28081405  0.06341534]
 [-0.47689368  2.2901819 ]
 [ 0.20938504  0.03449629]
 [ 1.28782302  2.20342476]
 [ 0.79762394  0.26584866]
 [-0.28081405  0.15017248]
 [ 0.0133054  -0.54388463]
 [-0.18277423  0.15017248]
 [-0.08473441  0.23692961]
 [ 0.0133054  -0.25469417]
 [ 2.17018137  1.104501  ]
 [-1.7514113   0.3526058 ]
 [ 1.87606192  0.12125343]
 

In [17]:
print(X_test)

[[-0.64807267  0.53080315]
 [ 0.07535729 -0.59737588]
 [-0.19592895  0.16490725]
 [-0.64807267  0.28687255]
 [-0.19592895 -0.59737588]
 [-0.9193589  -1.51211563]
 [-0.55764392 -1.66457226]
 [-0.1055002   2.26880869]
 [-1.7332176  -0.04853203]
 [ 0.88921599 -0.81081516]
 [-0.64807267 -0.6278672 ]
 [-0.82893016 -0.44491925]
 [-0.01507146 -0.44491925]
 [ 0.16578603  0.2258899 ]
 [-1.55236011  0.50031183]
 [-0.46721518  1.44554291]
 [-0.01507146  0.2258899 ]
 [-1.64278886  0.4698205 ]
 [ 1.61264594  1.84193014]
 [-0.19592895 -1.45113298]
 [-0.19592895 -0.68884985]
 [ 0.88921599  2.26880869]
 [ 0.34664352 -0.56688455]
 [ 0.88921599  1.07964701]
 [-1.28107388 -1.26818503]
 [ 1.07007347  2.17733471]
 [-0.82893016  0.53080315]
 [-0.73850141  0.31736388]
 [-0.01507146 -0.23147998]
 [-0.46721518  0.50031183]
 [-1.46193137  0.56129448]
 [-0.01507146  0.28687255]
 [ 1.79350343 -0.29246263]
 [-0.01507146 -0.5059019 ]
 [-1.19064513 -0.35344528]
 [-1.7332176  -0.53639323]
 [-1.37150262  0.3478552 ]
 

In [19]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [21]:
age=input("Enter the age of the person:")
salary=input("Enter the salary of the person:")
Age=float(age)
Salary=float(salary)
print(Age,Salary)

Enter the age of the person: 56
Enter the salary of the person: 910000


56.0 910000.0


In [23]:
print(lr.predict(sc.transform([[Age,Salary]])))

[1]


In [25]:
Y_pred=lr.predict(X_test)

In [27]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [29]:
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),y_test.reshape(len(y_test,),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]]


In [31]:
data.columns

Index(['Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [35]:
data.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [37]:
data.describe

<bound method NDFrame.describe of      Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]>

In [41]:
datas=pd.get_dummies(data,columns=['Purchased'],drop_first=True)

In [43]:
datas

Age  EstimatedSalary  Purchased_1
0     19            19000        False
1     35            20000        False
2     26            43000        False
3     27            57000        False
4     19            76000        False
..   ...              ...          ...
395   46            41000         True
396   51            23000         True
397   50            20000         True
398   36            33000        False
399   49            36000         True

[400 rows x 3 columns]

In [45]:
bg=pd.get_dummies(data,columns=['Age'],drop_first=True)

In [47]:
bg

EstimatedSalary  Purchased  Age_19  Age_20  Age_21  Age_22  Age_23  \
0              19000          0    True   False   False   False   False   
1              20000          0   False   False   False   False   False   
2              43000          0   False   False   False   False   False   
3              57000          0   False   False   False   False   False   
4              76000          0    True   False   False   False   False   
..               ...        ...     ...     ...     ...     ...     ...   
395            41000          1   False   False   False   False   False   
396            23000          1   False   False   False   False   False   
397            20000          1   False   False   False   False   False   
398            33000          0   False   False   False   False   False   
399            36000          1   False   False   False   False   False   

     Age_24  Age_25  Age_26  ...  Age_51  Age_52  Age_53  Age_54  Age_55  \
0     False   False   False  ...   False   False   False   False   False   
1     False   False   False  ...   False   False   False   False   False   
2     False   False    True  ...   False   False   False   False   False   
3     False   False   False  ...   False   False   False   False   False   
4     False   False   False  ...   False   False   False   False   False   
..      ...     ...     ...  ...     ...     ...     ...     ...     ...   
395   False   False   False  ...   False   False   False   False   False   
396   False   False   False  ...    True   False   False   False   False   
397   False   False   False  ...   False   False   False   False   False   
398   False   False   False  ...   False   False   False   False   False   
399   False   False   False  ...   False   False   False   False   False   

     Age_56  Age_57  Age_58  Age_59  Age_60  
0     False   False   False   False   False  
1     False   False   False   False   False  
2     False   False   False   False   False  
3     False   False   False   False   False  
4     False   False   False   False   False  
..      ...     ...     ...     ...     ...  
395   False   False   False   False   False  
396   False   False   False   False   False  
397   False   False   False   False   False  
398   False   False   False   False   False  
399   False   False   False   False   False  

[400 rows x 44 columns]

In [53]:
x=data.drop(['Age'],axis=1)
y=data['Age']

In [55]:
x

EstimatedSalary  Purchased
0              19000          0
1              20000          0
2              43000          0
3              57000          0
4              76000          0
..               ...        ...
395            41000          1
396            23000          1
397            20000          1
398            33000          0
399            36000          1

[400 rows x 2 columns]

In [57]:
y

0      19
1      35
2      26
3      27
4      19
       ..
395    46
396    51
397    50
398    36
399    49
Name: Age, Length: 400, dtype: int64

In [59]:
a=data.drop(['Purchased'],axis=1)
b=data['Purchased']

In [61]:
a

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [63]:
b

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [65]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [67]:
trans_mm = MinMaxScaler()
trans_ss = StandardScaler()

In [69]:
df_mm = trans_mm.fit_transform(x)
pd.DataFrame(df_mm)

0    1
0    0.029630  0.0
1    0.037037  0.0
2    0.207407  0.0
3    0.311111  0.0
4    0.451852  0.0
..        ...  ...
395  0.192593  1.0
396  0.059259  1.0
397  0.037037  1.0
398  0.133333  0.0
399  0.155556  1.0

[400 rows x 2 columns]